### ISSUE TITLE
Have to use fully qualified path to run sqlcl to avoid issue with GNU sql that's installed on "ubutu-latest"

### ISSUE THREAD

**Issue by navratil** [gvenzl/setup-oracle-sqlcl#2]
Took me some time to realize there is a name conflict: "sql" in "ubuntu-latest" points to GNU sql

```
GNU sql 20210822
Copyright (C) 2009,2010,2011,2012,2013,2014,2015,2016,2017
Ole Tange and Free Software Foundation, Inc.
```

Using full path to sqlcl works 

``` yaml
      - name: Run SQLcl
        run: |
          ${SQLCL_HOME}/bin/sql <arguments>
```

Perhaps updating the documentation will save time for others.
